---
title: "Ingest Census Data"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      echo = FALSE)

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(mapboxapi)
library(leaflet)
library(censusapi)
options(tigris_use_cache = TRUE)

# Parameters
wd <- getwd()
data_folder <- "/data/"
Sys.setenv(CENSUS_KEY="99ccb52a629609683f17f804ca875115e3f0804c")
mapbox <- "sk.eyJ1IjoiZnJhbmNpbmVzdGVwaGVucyIsImEiOiJja2ljb3VrczMwdDdhMnhsNjA4Yjh1c2h1In0.WJjq6TysT6zZZnaxsN0s5g"
token <- "pk.eyJ1IjoiZnJhbmNpbmVzdGVwaGVucyIsImEiOiJjazhobGNramgwMDF1M2Zsa2tieHV2eDF1In0.60HwmeTBd_q8TY5yAA0kZw"
mb_access_token(token, overwrite = TRUE)
readRenviron("~/.Renviron")

state_fips <- "08"
county_fips <- "031"
state_county_fips <- "state:08+county:031"
```



# Import Data
```{r}
# 
zillow_nhoods <- st_read(paste0(wd,  
                                data_folder, 
                                "Zillow_Neighborhoods/ZillowNeighborhoods.gdb"))

city_denver_nhoods <- st_read(paste0(wd,  
                                data_folder, 
                               "american_community_survey_nbrhd_2013_2017/american_community_survey_nbrhd_2013_2017.shp"))


parks <- st_read(paste0(wd, 
                        data_folder,
                        "parks/parks.shp"))

bg_sf <- block_groups(state = state_fips, county = county_fips)

bg_sf_transformed <- bg_sf %>% 
  st_transform(., crs = 2232)

```

```{r}
nhoods <- zillow_nhoods %>% 
  filter(State == "CO" & County == "Denver") 


nhood_name_vector <- nhoods %>% 
  pull(Name)



bg_assigned_nhoods <- bg_sf_transformed %>% 
  st_join(., nhoods %>% 
            st_transform(., crs = 2232),
          by = st_intersects)
  
st_crs(bg_sf)


```


```{r}
# Census Geography
counties_sf <- counties(state = state_fips, year = 2022)

county_sf <- counties_sf %>% 
  filter(COUNTYFP == county_fips)

tracts_sf <- tracts(state = state_fips, county = county_fips)

```

```{r}
# Demographics
all_demog_vars <- getCensus(
    name = "acs/acs5",
    vintage = 2021,
    region = "tract:*",
    regionin = state_county_fips,
    vars = c(
      # Age
      "B01001_001E",
      "B01001_011E",
      "B01001_012E",
      "B01001_035E",
      "B01001_036E",
      # Median Gross Rent
      #"B25064_001E",
      # Gross Rent by bedrooms 
      "B25031_001E",
      "B25031_004E",
      "B25031_005E",
      # Highest Educational Attainment
      "B15002_001E",
      "B15002_015E",
      "B15002_016E",
      "B15002_017E",
      "B15002_018E",
      "B15002_032E",
      "B15002_033E",
      "B15002_034E",
      "B15002_035E",
      # Median Household Income
      "B19013_001E"
    )
  ) %>%
  mutate(
    tract = paste0(state, county, tract),
    percent_latemillenials = ((B01001_011E + B01001_012E + B01001_035E + B01001_036E) / B01001_001E) * 100,
    percent_baplus = ((B15002_015E + B15002_016E + B15002_017E + B15002_018E + B15002_032E + B15002_033E + B15002_034E + B15002_035E) / B15002_001E) * 100
  ) %>% 
  rename(population = "B01001_001E",
         median_rent = "B25031_001E",
         median_rent_2br = "B25031_004E",
         median_rent_3br = "B25031_005E",
         median_hhinc = "B19013_001E"
         ) %>% 
  mutate(across(where(is.numeric), ~ifelse(.x < 0, NA, .x)))

head(all_demog_vars)

# Merge Demographics onto Tract Shapefile
tracts_demogs_sf <- tracts_sf %>% 
  left_join(., all_demog_vars, by = c("GEOID" = "tract"))
```


# Draw Isochrone
```{r}

# Create accessibility isochrones
isochrone <- mb_isochrone(
  location = c(lng, lat),
  profile = "driving-traffic",
  time = c(20, 25)
  #depart_at = "2022-03-31T09:00"
)
```

```{r}

leaflet() %>% 
  #setView(lng = lng, lat = lat, zoom = 11) %>%
  addMapboxTiles(
    style_id = "streets-v9",
    username = "mapbox"
  ) %>%
  # TRACTS LAYERS
  addPolygons(
    data = bg_assigned_nhoods %>% 
      st_transform(., crs = 4326),
    fill = TRUE,
    fillColor = "orange",
    fillOpacity = 0.75,
    color = "white",
    opacity = 0.5, 
    weight = 0.4,
    label = ~paste0(Name),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
    #,
    #group = "All Rentals"
  ) 
```



------

# Create Maps

### Rent
```{r}
# Color Palettes
rent_pal <- colorNumeric(
  palette = "Greens",
  domain = tracts_demogs_sf$median_rent
)

rent2br_pal <- colorNumeric(
  palette = "Greens",
  domain = tracts_demogs_sf$median_rent_2br
)


```

```{r}
# Rent Overall
leaflet() %>% 
  #setView(lng = lng, lat = lat, zoom = 11) %>%
  addMapboxTiles(
    style_id = "streets-v9",
    username = "mapbox"
  ) %>%
  # addMarkers(data = point_locations_sf
  #                  #radius = 0.8,
  #                  #color = "navy"
  #                    ) %>% 
  # TRACTS LAYERS
  addPolygons(
    data = tracts_demogs_sf,
    fill = TRUE,
    fillColor = ~rent_pal(median_rent),
    fillOpacity = 0.75,
    color = "white",
    opacity = 0.5, 
    weight = 0.4,
    label = ~paste0("Median Rent: $", median_rent 
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ),
    group = "All Rentals"
  ) %>%
  addPolygons(
    data = tracts_demogs_sf,
    fill = TRUE,
    fillColor = ~rent_pal(median_rent_2br),
    fillOpacity = 0.75,
    color = "white",
    opacity = 0.5,
    weight = 0.4,
    label = ~paste0("2-Bedroom Median Rent: $", median_rent_2br
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ),
    group = "2 Bedroom Rentals"

  ) %>%
  # ISOCHRONE
  # addPolygons(
  #   data = isochrone %>% 
  #     filter(time == 20),
  #   fill = FALSE,
  #   stroke = TRUE,
  #   weight = 1.2,
  #   color = "navy", 
  #   opacity = 0.9, 
  #   dashArray = "3",
  #   group = "20-Minute Work Commute"
  # ) %>% 
  addLegend("bottomright", pal = rent_pal, values = tracts_demogs_sf$median_rent,
    title = "Median Gross Rents",
    labFormat = labelFormat(prefix = "$", big.mark = ","),
    group = "All Rentals"
  ) %>%
  addLegend("bottomright", pal = rent_pal, title="2 Bedroom Rentals",
            values = tracts_demogs_sf$median_rent_2br, group="2 Bedroom Rentals") %>%
  addLayersControl(
    overlayGroups = c("All Rentals", "2 Bedroom Rentals"),
    position = "topright",
    options = layersControlOptions(collapsed = F)
  )  %>% 
  hideGroup("2 Bedroom Rentals")


```

### Education/Income
```{r}
# Color Palettes
ed_pal <- colorNumeric(
  palette = "Greens",
  domain = tracts_demogs_sf$percent_baplus
)

medhhinc_pal <- colorNumeric(
  palette = "Greens",
  domain = tracts_demogs_sf$median_hhinc
)


```

```{r}
# Rent Overall
leaflet() %>% 
  #setView(lng = lng, lat = lat, zoom = 11) %>%
  addMapboxTiles(
    style_id = "streets-v9",
    username = "mapbox"
  ) %>%
  # addMarkers(data = point_locations_sf
  #                  #radius = 0.8,
  #                  #color = "navy"
  #                    ) %>% 
  # TRACTS LAYERS
  addPolygons(
    data = tracts_demogs_sf,
    fill = TRUE,
    fillColor = ~ed_pal(percent_baplus),
    fillOpacity = 0.75,
    color = "white",
    opacity = 0.5, 
    weight = 0.4,
    label = ~paste0("Residents with at least a BA: ", round(percent_baplus, digits= 1), "%"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ),
    group = "Education"
  ) %>%
  addPolygons(
    data = tracts_demogs_sf,
    fill = TRUE,
    fillColor = ~medhhinc_pal(median_hhinc),
    fillOpacity = 0.75,
    color = "white",
    opacity = 0.5,
    weight = 0.4,
    label = ~paste0("Median Household Income: $", median_hhinc
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ),
    group = "Income"

  ) %>%
  # ISOCHRONE
  # addPolygons(
  #   data = isochrone %>% 
  #     filter(time == 20),
  #   fill = FALSE,
  #   stroke = TRUE,
  #   weight = 1.2,
  #   color = "navy", 
  #   opacity = 0.9, 
  #   dashArray = "3",
  #   group = "20-Minute Work Commute"
  # ) %>% 
  addLegend("bottomright", pal = ed_pal, values = tracts_demogs_sf$percent_baplus,
    title = "% Residents with a Bacherlors Degree",
    labFormat = labelFormat(suffix = "%"),
    group = "Education"
  ) %>%
  addLegend("bottomright", pal = medhhinc_pal, title="Income",
            values = tracts_demogs_sf$median_hhinc, group="Income") %>%
  addLayersControl(
    overlayGroups = c("Education", "Income"),
    position = "topright",
    options = layersControlOptions(collapsed = F)
  )  %>% 
  hideGroup("Income")


```

### Age/Household Comp

```{r}


```

```{r}


```

